import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Spec 045 PR-6 (part 1) — Point-in-time feature snapshot table.
 *
 * THE cornerstone architectural piece for v3 model retraining.
 *
 * Without this table, training a new model would re-read CURRENT
 * feature values for every PAST loan and feed them into the model.
 * That leaks future-of-decision information (e.g., a loan from March
 * 2026 trained with `n_prior_real_defaults` reflecting defaults that
 * happened in April → the model "knows" the future). AUC inflates
 * artificially in offline evaluation but the model fails in
 * production because real first-time-decisions never have access to
 * future history.
 *
 * This table freezes EVERY scoring decision the system makes:
 *   - admission scoring (waitlist join / first contact)
 *   - borrow-time scoring (every loan request, post-PR-5 wiring)
 *   - training_synth (the historical replay generated by PR-6 part 2)
 *
 * Each row is the *exact* feature vector that was passed to the
 * model at decision time, plus the model's prediction. Training
 * reads from this table; inference writes to it. One source of
 * truth, no temporal drift.
 *
 * The `featureVector` is JSONB so the schema is feature-set-agnostic:
 * adding/removing features in the model never requires a column
 * migration. Indexes are picked for the two hot read patterns:
 *   - "all snapshots for user U over time" (user feature timeline)
 *   - "all admission snapshots before time T" (training set extraction)
 */
export class AddRiskFeatureSnapshots20260507200000
  implements MigrationInterface
{
  name = 'AddRiskFeatureSnapshots20260507200000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "risk_feature_snapshots" (
        "id" BIGSERIAL PRIMARY KEY,
        "userId" INT NOT NULL REFERENCES "users"("id"),
        "loanId" INT NULL REFERENCES "loans"("id"),
        "decisionTimestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "decisionType" VARCHAR(20) NOT NULL,
        "featureVector" JSONB NOT NULL,
        "modelVersion" VARCHAR(40) NULL,
        "pDefault" DECIMAL(6,4) NULL,
        "decision" VARCHAR(20) NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // Hot read 1: user timeline ("show me all snapshots for user U").
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_risk_feat_snap_user"
        ON "risk_feature_snapshots" ("userId", "decisionTimestamp" DESC)
    `);

    // Hot read 2: training set extraction by type + time cutoff.
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_risk_feat_snap_type_time"
        ON "risk_feature_snapshots" ("decisionType", "decisionTimestamp")
    `);

    // Idempotency guard: don't write 2 snapshots for the same decision.
    // Keyed by (user, timestamp, type) — admission vs borrow can coexist
    // at the same instant for different users; a burst of duplicate
    // requests for the SAME user within the same millisecond gets deduped.
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_risk_feat_snap_decision"
        ON "risk_feature_snapshots" ("userId", "decisionTimestamp", "decisionType")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "uq_risk_feat_snap_decision"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_risk_feat_snap_type_time"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_risk_feat_snap_user"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "risk_feature_snapshots"`);
  }
}
